### ISSUE TITLE
Store checklist

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#45]
We aim to get the app in stores as soon as we can. Steps that need to be completed:

- [x] Confirm name can be used 
- [x] Get app icon
- [x] Draft app description 
- [x] Screenshots for iOS, Android and UWP
- [x] Write steps for apple testing and share test account
- [x] Share GitHub repo
- [x] Update appstudio template item
- [x] Share/host documentation (pdf)
- [ ] Marketplace listing
- [ ] Esri labs website
- [x] Email announcement

**Comment by JohnHasthorpe** [comment]
Complete - closing
